### ISSUE TITLE
Static-scan run needs checking in kie-tools

### ISSUE THREAD

**Issue by baldimir** [IBM/kie-roadmap#35]
There is SonarQube run executed as part of static-scan step during the kie-tools build. The scan takes 5 hours to complete. It needs to be investigated, why the scan takes such long time and if it is possible to make it finish sooner.

**Comment by jstastny-cz** [comment]
Working through with the resolution.

The main reason was that scan was diving into `node_modules` directories. Moreover our `pnpm` build of each package has link to itself created in the `node_modules`, which was resulting in link loop detection in `sonarqube` (which also might have brought some perf overhead).

To resolve we need to exclude `node_modules` from the scan. Using plain `sonar.exclusions` for `node_modules` does not resolve the link loop detection warning, so logs are still full of `WARN` entries.

On the other hand, explicitly mentioning all `packages/*/src` directories in `sonar.sources` property does prevent the scan to consider `node_modules` directory altogether. The values need be relative paths in scope of `sonarqube` image, thus `/usr/src/` prefixed, separated by commas (no wildcard allowed).

Together with that, because the repo contains also java classes, property `sonar.java.binaries` needs to point at each `packages/*/target` dir, explicitly naming the directories separated by comma (no wildcard allowed).
